api/urls.py
from django.urls import path
from api import views

app_name = "api"
urlpatterns = [
    path("transact/",views.run_transaction,name="transact"),
    path("transact/verify/",views.verify_transaction,name="verify"),
    path("transact/resend/",views.resend_code,name="resend")
]

employers/urls.py
from django.urls import path
from employers import views

app_name = "employers"
urlpatterns = [
    path("",views.dashboard,name="dashboard"),
    path("add/", views.new_employer, name="new_employer"),
    path("admins/", views.admin_list, name="admins"),
    path("admins/<int:pk>/", views.admin_profile, name="admin_profile"),
    path("admins/<int:pk>/edit/", views.edit_admin, name="edit_admin"),
    path("settings/", views.edit_employer,name="settings"),
    path("departments/", views.dept_list,name="dept_list"),
    path("departments/add", views.new_department,name="new_dept"),
    path("departments/<int:pk>/edit", views.edit_department,name="edit_dept"),
    path("departments/<int:pk>/delete", views.delete_dept,name="delete_dept"),
    path("admins/add/", views.new_admin, name="new_admin"),
    path("employees/", views.employee_list, name="employee_list"),
    path("employees/<int:pk>/", views.employee_detail, name="employee_detail"),
    path("employees/add/", views.new_employee, name="new_employee"),
    path("employees/<int:pk>/edit/", views.edit_employee, name="edit_employee"),
    path("employees/<int:pk>/details/edit/", views.edit_details, name="edit_details"),
    path("employees/<int:pk>/activate/", views.activate_employee, name="activate_employee"),
    path("employees/upload/", views.upload_users, name="upload")
]

payroll/urls.py
from django.urls import path
from payroll import views

app_name = "payroll"
urlpatterns = [
    path("", views.payroll_list, name="payrolls"),
    path("generate/", views.generate_payrolls, name="gen_pay"),
    path("payslips/", views.generate_payslips, name="payslips")
]

payroll/models.py
import os
from decimal import Decimal
from django.db import models
from employers.models import Employee
from common.models import BaseModel
from common.gra import get_tax
from django.conf import settings

# Create your models here.


class Payroll(BaseModel):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    basic_salary = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)
    bonus = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)
    allowances = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)
    deductions = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)
    gross_salary = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)
    ssf_employee = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)
    ssf_employer = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)
    taxable_income = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)
    paye = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)
    net_salary = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)

    @property
    def employer(self):
        return self.employee.employer

    @property
    def month(self):
        return self.created_at.month

    @property
    def year(self):
        return self.created_at.year

    @property
    def name(self):
        return "{0}_{1}".format(self.month, self.year)

    def save(self, *args, **kwargs):
        self.basic_salary = self.employee.workdetail.basic_salary
        self.allowances = self.employee.paymentdetail.allowances
        self.bonus = self.employee.paymentdetail.bonus
        self.deductions = self.employee.paymentdetail.deductions
        self.gross_salary = self.basic_salary + self.bonus + self.allowances
        self.ssf_employee = self.gross_salary * settings.SSF_EMPLOYEE_RATE
        self.ssf_employer = self.gross_salary * settings.SSF_EMPLOYER_RATE
        self.taxable_income = self.gross_salary - self.ssf_employee
        self.paye = get_tax(self.taxable_income)
        self.net_salary = self.taxable_income - self.deductions
        super().save(*args, **kwargs)

employers/forms.py
from django import forms
from employers.models import Employee, Employer, Address, WorkDetail, PaymentDetail, Department, Administrator


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ("location", "postal_address", "phone", "email")


class AdministratorForm(forms.ModelForm):
    class Meta:
        model = Administrator
        fields = ("avatar", "role")


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ("first_name", "middle_name", "last_name","headshot",
                  "date_of_birth", "gender", "marital_status")


class WorkDetailForm(forms.ModelForm):
    class Meta:
        model = WorkDetail
        fields = ("department", "basic_salary",
                  "date_of_employment", "social_security_no")

    def __init__(self, employer, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["department"].queryset = Department.objects.filter(
            employer=employer)


class PaymentDetailForm(forms.ModelForm):
    class Meta:
        model = PaymentDetail
        fields = ("bonus", "allowances", "deductions")


class EmployerForm(forms.ModelForm):
    PAYROLL_DATE_CHOICES = [
        (i,str(i)) for i in range(1,30)
    ]
    payroll_date = forms.TypedChoiceField(choices=PAYROLL_DATE_CHOICES,initial=29, coerce=int)
    class Meta:
        model = Employer
        fields = ("name", "description", "logo","payroll_date")


class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ("name",)

class FileUploadForm(forms.Form):
    upload_file = forms.FileField()

    def clean_upload_file(self):
        upload_file = self.cleaned_data.get("upload_file")
        if upload_file:
            if upload_file.size > 2.5*1024*1024:
                raise forms.ValidationError("File size must be 2.5MB or less!")
            if not upload_file.name.endswith(".csv"):
                raise forms.ValidationError("Only csv files accepted!")
        return upload_file

employers/views.py
import datetime as dt
import csv
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from accounts.forms import SignUpForm
from employers.models import Employee, Employer, WorkDetail, PaymentDetail,Administrator, Department
from employers.forms import AddressForm, EmployeeForm, EmployerForm, DepartmentForm, WorkDetailForm, PaymentDetailForm, AdministratorForm, FileUploadForm
from common.decorators import admin_staff_required

# Create your views here.


@login_required
def dashboard(request):
    employer = request.user.administrator.employer
    return render(request, "employers/dashboard.html",{"employer":employer})


@login_required
def admin_list(request):
    employer = request.user.administrator.employer
    admins = Administrator.objects.filter(employer=employer)
    return render(request, "employers/users.html", {"admins": admins})


@login_required
def employee_list(request):
    employer = request.user.administrator.employer
    queryset = Employee.objects.filter(employer=employer)
    return render(request, "employers/employee_list.html", {"employees": queryset})


@login_required
@admin_staff_required
def new_employee(request):
    employer = request.user.administrator.employer
    if request.method == "POST":
        form = EmployeeForm(request.POST, request.FILES, prefix="employee")
        addr = AddressForm(request.POST, prefix="addr")
        if form.is_valid() and addr.is_valid():
            employee = form.save(commit=False)
            employee.created_by = request.user
            employee.employer = employer
            employee.address = addr.save()
            employee.save()
            return redirect("employers:employee_detail", pk=employee.pk)
    else:
        form = EmployeeForm(prefix="employee")
        addr = AddressForm(prefix="addr")
    return render(request, "employers/new_employee.html", {"form": form, "addr": addr})


@login_required
def edit_employee(request, pk):
    employer = request.user.administrator.employer
    obj = get_object_or_404(Employee.objects.filter(employer=employer), pk=pk)
    if request.method == "POST":
        form = EmployeeForm(request.POST, request.FILES,
                            instance=obj, prefix="employee")
        addr = AddressForm(request.POST, instance=obj.address, prefix="addr")
        if form.is_valid() and addr.is_valid():
            employee = form.save(commit=False)
            employee.edited_by = request.user
            addr.save()
            employee.save()
            return redirect("employers:employee_detail", pk=pk)
    else:
        form = EmployeeForm(instance=obj, prefix="employee")
        addr = AddressForm(instance=obj.address, prefix="addr")
    return render(request, "employers/new_employee.html", {"form": form, "addr": addr})


@login_required
def employee_detail(request, pk):
    employer = request.user.administrator.employer
    employee = get_object_or_404(
        Employee.objects.filter(employer=employer), pk=pk)
    return render(request, "employers/employee_detail.html", {"employee": employee})


@login_required
@admin_staff_required
def activate_employee(request, pk):
    employer = request.user.administrator.employer
    employee = get_object_or_404(
        Employee.objects.filter(employer=employer), pk=pk)
    if employee.active:
        employee.active = False
    else:
        employee.active = True
    employee.save()
    return redirect("employers:employee_list")


@login_required
@admin_staff_required
def edit_details(request, pk):
    employer = request.user.administrator.employer
    employee = get_object_or_404(
        Employee.objects.filter(employer=employer), pk=pk)
    if request.method == "POST":
        work = WorkDetailForm(employer, request.POST,
                              instance=employee.workdetail, prefix="work")
        payment = PaymentDetailForm(
            request.POST, instance=employee.paymentdetail, prefix="pay")
        if work.is_valid() and payment.is_valid():
            work.save()
            payment.save()
            return redirect("employers:employee_detail", pk=employee.pk)
    else:
        work = WorkDetailForm(
            employer, instance=employee.workdetail, prefix="work")
        payment = PaymentDetailForm(
            instance=employee.paymentdetail, prefix="pay")
    return render(request, "employers/edit_details.html", {"work": work, "payment": payment})


@login_required
@admin_staff_required
def new_employer(request):
    if request.method == "POST":
        form = EmployerForm(request.POST, request.FILES, prefix="employer")
        addr = AddressForm(request.POST, prefix="addr")
        if form.is_valid() and addr.is_valid():
            employer = form.save(commit=False)
            employer.address = addr.save()
            employer.created_by = request.user
            employer.save()
            administrator = request.user.administrator
            administrator.employer = employer
            administrator.save()
            return redirect("employers:new_dept")
    else:
        form = EmployerForm(prefix="employer")
        addr = AddressForm(prefix="addr")
    return render(request, "employers/new_employer.html", {"form": form, "addr": addr})


@login_required
@admin_staff_required
def edit_employer(request):
    obj = request.user.administrator.employer
    if request.method == "POST":
        form = EmployerForm(request.POST, request.FILES,
                            instance=obj, prefix="employer")
        addr = AddressForm(request.POST, instance=obj.address, prefix="addr")
        if form.is_valid() and addr.is_valid():
            employer = form.save(commit=False)
            employer.edited_by = request.user
            employer.save()
            addr.save()
            return redirect("employers:dashboard")
    else:
        form = EmployerForm(prefix="employer", instance=obj)
        addr = AddressForm(prefix="addr", instance=obj.address)
    return render(request, "employers/settings.html", {"form": form, "addr": addr})


@login_required
@admin_staff_required
def new_department(request):
    employer = request.user.administrator.employer
    if request.method == "POST":
        form = DepartmentForm(request.POST)
        if form.is_valid():
            dept = form.save(commit=False)
            dept.created_by = request.user
            dept.employer = employer
            dept.save()
            return redirect("employers:dept_list")
    else:
        form = DepartmentForm()
    return render(request, "employers/new_dept.html", {"form": form})


@login_required
@admin_staff_required
def edit_department(request, pk):
    employer = request.user.administrator.employer
    obj = get_object_or_404(
        Department.objects.filter(employer=employer), pk=pk)
    if request.method == "POST":
        form = DepartmentForm(request.POST, instance=obj)
        if form.is_valid():
            dept = form.save(commit=False)
            dept.edited_by = request.user
            dept.save()
            return redirect("employers:dept_list")
    else:
        form = DepartmentForm(instance=obj)
    return render(request, "employers/new_dept.html", {"form": form})


@login_required
def dept_list(request):
    employer = request.user.administrator.employer
    queryset = Department.objects.filter(employer=employer)
    return render(request, "employers/dept_list.html", {"departments": queryset})


@login_required
@admin_staff_required
def delete_dept(request, pk):
    employer = request.user.administrator.employer
    obj = get_object_or_404(
        Department.objects.filter(employer=employer), pk=pk)
    obj.delete()
    return redirect("employers:dept_list")


@login_required
@admin_staff_required
def new_admin(request):
    employer = request.user.administrator.employer
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            Administrator.objects.create(
                user=user, employer=employer, role="regular", created_by=request.user)
            return redirect("employers:admins")
    else:
        form = SignUpForm()
    return render(request, "employers/new_admin.html", {"form": form})

@login_required
@admin_staff_required
def edit_admin(request,pk):
    employer = request.user.administrator.employer
    obj = get_object_or_404(Administrator.objects.filter(employer=employer),pk=pk)
    if request.method == "POST":
        form = SignUpForm(request.POST, instance=obj.user,prefix="form")
        admin = AdministratorForm(request.POST,request.FILES,instance=obj,prefix="admin")
        if form.is_valid() and admin.is_valid():
            admin.save(commit=False)
            admin.edited_by = request.user
            form.save()    
            return redirect("employers:admins")
    else:
        form = SignUpForm(instance=obj.user,prefix="form")
        admin = AdministratorForm(instance=obj,prefix="admin")
    return render(request, "employers/new_admin.html", {"form": form,"admin":admin})

@login_required
def admin_profile(request,pk):
    employer = request.user.administrator.employer
    admin = get_object_or_404(Administrator.objects.filter(employer=employer),pk=pk)
    return render(request,"employers/profile.html",{"admin":admin})

@login_required
@admin_staff_required
def upload_users(request):
    if request.method == "POST":
        form = FileUploadForm(request.POST,request.FILES)
        if form.is_valid():
            csv_file = request.FILES.get("upload_file")
            file_data = csv_file.read().decode("utf-8").split("\n")
            lines = csv.DictReader(file_data)
            return render(request,"employers/preview.html",{"lines":lines})
    else:
        form = FileUploadForm()
    return render(request,"employers/upload.html",{"form":form})

payroll/views.py
import datetime as dt
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from payroll.models import Employee, Payroll
from common.decorators import admin_staff_required

# Create your views here.
@login_required
@admin_staff_required
def generate_payrolls(request):
    employer = request.user.administrator.employer
    for employee in Employee.objects.filter(employer=employer, active=True):
        Payroll.objects.create(employee=employee)
    return redirect("payroll:payrolls")


@login_required
def payroll_list(request):
    employer = request.user.administrator.employer
    payrolls = Payroll.objects.filter(employee__employer=employer)
    return render(request, "payroll/payrolls.html", {"payrolls": payrolls})


@login_required
def generate_payslips(request):
    return render(request, "payroll/payslips.html")

employers/templates/employers/dept_list.html
{% extends "employer_base.html" %} 
{% block title %}Departments{% endblock %} 
{% block content %}
<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="row">
            <div class="col-sm-8">
                <h4 class="page-title">Departments</h4>
            </div>
            <div class="col-sm-4 text-right m-b-30">
                <a href="{% url 'employers:new_dept' %}" class="btn btn-primary rounded">
                    <i class="fa fa-plus"></i> Add New Department</a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div>
                    <table class="table table-striped custom-table m-b-0 datatable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Department Name</th>
                                <th class="text-right">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for dept in departments %}
                            <tr>
                                <td>{{forloop.counter}} .</td>
                                <td>{{dept.name}}</td>
                                <td class="text-right">
                                    <div class="dropdown">
                                        <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                            <i class="fa fa-ellipsis-v"></i>
                                        </a>
                                        <ul class="dropdown-menu pull-right">
                                            <li>
                                                <a href="{% url 'employers:edit_dept' pk=dept.pk %}">
                                                    <i class="fa fa-pencil m-r-5"></i> Edit</a>
                                            </li>
                                            <li>
                                                <a href="{% url 'employers:delete_dept' pk=dept.pk %}" title="Delete">
                                                    <i class="fa fa-trash-o m-r-5"></i> Delete</a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                            {% empty %} {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

employers/templates/employers/new_admin.html
{% extends "employer_base.html" %} 
{% load static %} 
{% load widget_tweaks %} 
{% block title %}
    {% if form.instance.pk %}
        Add Admin
    {% else %}
        Edit Admin
    {% endif %}
{% endblock%} 
{% block content %}
<div class="page-wrapper">
    <div class="content container-fluid">
        <div id="add_employee">
            <div class="modal-header">
                {% if form.instance.pk %}
                    <h4 class="modal-title"> Add Admin</h4>
                {% else %}
                    <h4 class="modal-title"> Edit Admin</h4>
                {% endif %}
            </div>
            <div class="modal-body">
                <form method="POST" enctype="multipart/form-data">
                    {% include "form.html" %}
                    {% include "admin.html" %}
                    <div class="form-group text-center">
                        <button class="btn btn-primary btn-block account-btn" type="submit">Add</button>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

employers/templates/employers/new_dept.html
{% extends "employer_base.html" %} 
{% load static %} {% load widget_tweaks %} 
{% block title %}New Admin {% endblock%} 
{% block content %}
<div class="page-wrapper">
    <div class="content container-fluid">
        <div id="add_department">
            <div class="modal-header">
                <h4 class="modal-title"> Add Department</h4>
            </div>
            <div class="modal-body">
                <form method="POST">
                    {% include "form.html" %}
                    <div class="m-t-20 text-center">
                        <button class="btn btn-primary" type="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

employers/templates/employers/payrolls.html
{% extends "employer_base.html" %}
{% load humanize %}
{% block title %}Payroll {% endblock %}
{% block content %}
    <div class="page-wrapper">
        <div class="content container-fluid">
            <div class="row">
                <div class="col-xs-4">
                    <h4 class="page-title">Employee Payroll</h4>
                </div>
                <div class="col-xs-8 text-right m-b-30">
                    <a href="{% url 'employers:gen_pay' %}" class="btn btn-primary rounded pull-right">
                        <i class="fa fa-plus"></i> Generate Payrolls</a>
                </div>
            </div>
            <div class="row filter-row">
                <div class="col-sm-3 col-md-2 col-xs-6">
                    <div class="form-group form-focus">
                        <label class="control-label">Employee Name</label>
                        <input type="text" class="form-control floating" />
                    </div>
                </div>
                <div class="col-sm-3 col-md-2 col-xs-6">
                    <div class="form-group form-focus select-focus">
                        <label class="control-label">Role</label>
                        <select class="select floating">
                            <option value=""> -- Select -- </option>
                            <option value="">Employee</option>
                            <option value="1">Manager</option>
                        </select>
                    </div>
                </div>
                <div class="col-sm-3 col-md-2 col-xs-6">
                    <div class="form-group form-focus select-focus">
                        <label class="control-label">Leave Status</label>
                        <select class="select floating">
                            <option value=""> -- Select -- </option>
                            <option value="0"> Pending </option>
                            <option value="1"> Approved </option>
                            <option value="2"> Rejected </option>
                        </select>
                    </div>
                </div>
                <div class="col-sm-3 col-md-2 col-xs-6">
                    <div class="form-group form-focus">
                        <label class="control-label">From</label>
                        <div class="cal-icon">
                            <input class="form-control floating datetimepicker" type="text">
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 col-md-2 col-xs-6">
                    <div class="form-group form-focus">
                        <label class="control-label">To</label>
                        <div class="cal-icon">
                            <input class="form-control floating datetimepicker" type="text">
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 col-md-2 col-xs-6">
                    <a href="#" class="btn btn-success btn-block"> Search </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table table-striped custom-table datatable">
                            <thead>
                                <tr>
                                    <th style="width:10%;">Employee</th>
                                    <th>Basic Salary</th>
                                    <th>Bonus</th>
                                    <th>Allowances</th>
                                    <th>Gross Salary</th>
                                    <th>SSF</th>
                                    <th>SSF Employer</th>
                                    <th>Taxable</th>
                                    <th>P.A.Y.E</th>
                                    <th>Net Salary</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for payroll in payrolls %}
                                    <tr>
                                        <td>{{payroll.employee}}</td>
                                        <td>{{payroll.basic_salary|intcomma}}</td>
                                        <td>{{payroll.bonus|intcomma}}</td>
                                        <td>{{payroll.allowances|intcomma}}</td>
                                        <td>{{payroll.gross_salary|intcomma}}</td>
                                        <td>{{payroll.ssf_employee|intcomma}}</td>
                                        <td>{{payroll.ssf_employer|intcomma}}</td>
                                        <td>{{payroll.taxable_income|intcomma}}</td>
                                        <td>{{payroll.paye|intcomma}}</td>
                                        <td>{{payroll.net_salary|intcomma}}</td>
                                    </tr>
                                {% empty %}
                                    <p class="alert alert-danger">Sorry No Payrolls yet</p>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

employers/templates/employers/users.html
{% extends "employer_base.html" %}
{% block title %}Users{% endblock %}
{% block content %}
    <div class="page-wrapper">
        <div class="content container-fluid">
            <div class="row">
                <div class="col-xs-4">
                    <h4 class="page-title">Administrators</h4>
                </div>
                <div class="col-xs-8 text-right m-b-20">
                    <a href="{% url 'employers:new_admin' %}" class="btn btn-primary rounded pull-right">
                        <i class="fa fa-plus"></i> Add Admin</a>
                </div>
            </div>
            <div class="row filter-row">
                <div class="col-sm-3 col-xs-6">
                    <div class="form-group ">
                        <label class="control-label">Admin ID</label>
                        <input type="text" class="form-control floating" />
                    </div>
                </div>
                <div class="col-sm-3 col-xs-6">
                    <div class="form-group ">
                        <label class="control-label">Admin Name</label>
                        <input type="text" class="form-control floating" />
                    </div>
                </div>
                <div class="col-sm-3 col-xs-6">
                    <div class="form-group  select-focus">
                        <label class="control-label">Designation</label>
                        <select class="select floating">
                            <option value="">Select Designation</option>
                            <option value="">Web Developer</option>
                            <option value="1">Web Designer</option>
                            <option value="1">Android Developer</option>
                            <option value="1">Ios Developer</option>
                        </select>
                    </div>
                </div>
                <div class="col-sm-3 col-xs-6">
                    <a href="#" class="btn btn-success btn-block"> Search </a>
                </div>
            </div>
            <div class="row staff-grid-row">
                {% for admin in admins %}
                    <div class="col-md-4 col-sm-4 col-xs-6 col-lg-3">
                        <div class="profile-widget">
                            <div class="profile-img">
                                <a href="{% url 'employers:admin_profile' pk=admin.pk %}">
                                    <img class="avatar" src="" alt="admin">
                                </a>
                            </div>
                            <div class="dropdown profile-action">
                                <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-ellipsis-v"></i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li>
                                        <a href="{% url 'employers:edit_admin' pk=admin.pk %}">
                                            <i class="fa fa-pencil m-r-5"></i> Edit</a>
                                    </li>
                                    <li>
                                        <a href="#" data-toggle="modal" data-target="#delete_employee">
                                            <i class="fa fa-trash-o m-r-5"></i> Delete</a>
                                    </li>
                                </ul>
                            </div>
                            <h4 class="user-name m-t-10 m-b-0 text-ellipsis">
                                <a href="{% url 'employers:admin_profile' pk=admin.pk %}">{{admin.user.get_full_name}}</a>
                            </h4>
                            <div class="small text-muted">{{admin.role}}</div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}