accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/<str:user_type>/", views.signup, name="signup"),
]

api/urls.py
from django.urls import path
from api import views

app_name = "api"
urlpatterns = [
    path("transact/",views.run_transaction,name="transact"),
    path("transact/verify/",views.verify_transaction,name="verify"),
    path("transact/resend/",views.resend_code,name="resend")
]

employers/urls.py
from django.urls import path
from employers import views

app_name = "employers"
urlpatterns = [
    path("",views.dashboard,name="dashboard"),
    path("add/", views.new_employer, name="new_employer"),
    path("admins/", views.admin_list, name="admins"),
    path("admins/<int:pk>/", views.admin_profile, name="admin_profile"),
    path("admins/<int:pk>/edit/", views.edit_admin, name="edit_admin"),
    path("settings/", views.edit_employer,name="settings"),
    path("departments/", views.dept_list,name="dept_list"),
    path("departments/add", views.new_department,name="new_dept"),
    path("departments/<int:pk>/edit", views.edit_department,name="edit_dept"),
    path("departments/<int:pk>/delete", views.delete_dept,name="delete_dept"),
    path("admins/add/", views.new_admin, name="new_admin"),
    path("employees/", views.employee_list, name="employee_list"),
    path("employees/<int:pk>/", views.employee_detail, name="employee_detail"),
    path("employees/add/", views.new_employee, name="new_employee"),
    path("employees/<int:pk>/edit/", views.edit_employee, name="edit_employee"),
    path("employees/<int:pk>/details/edit/", views.edit_details, name="edit_details"),
    path("employees/<int:pk>/activate/", views.activate_employee, name="activate_employee"),
    path("employees/upload/", views.upload_users, name="upload")
]

payroll/urls.py
from django.urls import path
from payroll import views

app_name = "payroll"
urlpatterns = [
    path("", views.payroll_list, name="payrolls"),
    path("generate/", views.generate_payrolls, name="gen_pay"),
    path("payslips/", views.generate_payslips, name="payslips")
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from common.models import BaseModel

# Create your models here.


class Profile(models.Model):
    """
    Abstract Base Class for individuals in an employee with Login abilities
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role_choices = (
        ("admin", "Admin"),
        ("regular", "Regular")
    )
    role = models.CharField(
        max_length=10, choices=role_choices, default="regular")

    class Meta:
        abstract = True

accounts/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name",
                  "email", "password1", "password2")


class ProfileForm(UserCreationForm):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email")

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth import login, authenticate, logout
from django.core.exceptions import ViewDoesNotExist
from django.contrib.auth.forms import AuthenticationForm
from accounts.forms import SignUpForm
from employers.models import Administrator
from stores.models import StoreUser
# Create your views here.


def signup(request, user_type):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            if user_type == "employer":
                Administrator.objects.create(user=user, role="admin",created_by=user)
                return redirect("employers:new_employer")
            elif user_type == "store":
                StoreUser.objects.create(user=user, role="admin",created_by=user)
                return redirect("stores:new_store")
            else:
                raise ViewDoesNotExist
    else:
        form = SignUpForm()
    return render(request, "accounts/signup.html", {"form": form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(request,data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username,password=password)
            if user is not None:
                login(request,user)
                if hasattr(user,"storeuser"):
                    return redirect("stores:dashboard")
                return redirect("employers:dashboard")
    else:
        form = AuthenticationForm()
        user = auth.get_user(request)
        if user.is_authenticated:
            if hasattr(user, "storeuser"):
                return redirect("stores:dashboard")
            elif hasattr(user, "administrator"):
                return redirect("employers:dashboard")
            else:
                raise ViewDoesNotExist
    return render(request,"accounts/login.html",{"form":form})

def logout_view(request):
    logout(request)
    return redirect("accounts:login")

templates/accounts.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <!--[if lt IE 9]>
			<script src="js//html5shiv.min.js"></script>
			<script src="js/respond.min.js"></script>
		<![endif]-->
</head>

<body>
    <div class="main-wrapper">
        {% block content %}
        
        {% endblock %}
    </div>
    <div class="sidebar-overlay" data-reff="#sidebar"></div>
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/app.js' %}"></script>
</body>

</html>

templates/address.html
{% load widget_tweaks %}
{% csrf_token %} 
{% if addr.non_field_errors %}
    <div class="alert alert-danger">
        {% for error in addr.non_field_errors %} {{error}} {% endfor %}
    </div>
{% endif %} 
{% for hidden in addr.hidden_fields %} {{ hidden.errors }}{{ hidden }} {% endfor %} 
{% for field in addr.visible_fields %}
    <div class="form-group">
        <label class="control-label" for="{{ field.id_for_label }}">
            {{ field.label }}
        </label>
        {% if addr.is_bound %} 
            {% if field.errors %} 
                {% render_field field class="form-control is-invalid" %} 
                {% for error in field.errors %}
                    <span class="help-block text-danger">
                        {{ error }}
                    </span>
                {% endfor %} 
            {% else %} 
                {% render_field field class="form-control is-valid" %} 
            {% endif %} 
        {% else %} 
            {% render_field field class="form-control" %} 
        {% endif %} 
    </div>
{% endfor %}

templates/admin.html
{% load widget_tweaks %}
{% csrf_token %}
{% if admin.non_field_errors %}
    <div class="alert alert-danger">
        {% for error in admin.non_field_errors %}
            {{error}}
        {% endfor %}
    </div>
{% endif %}

{% for hidden in admin.hidden_fields %} {{ hidden.errors }}{{ hidden }} {% endfor %} 
{% for field in admin.visible_fields %}
    <div class="form-group">
        <label class="control-label" for="{{ field.id_for_label }}">
            {{ field.label }}
        </label>
        {% if admin.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                    <span class="help-block text-danger">
                        {{ error }}
                    </span>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}
        {% else %}
            {% render_field field class="form-control" %}
        {% endif %}   
    </div>
{% endfor %}

templates/employer_base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
        <title>Advancia | {% block title %}{% endblock %}</title>
		<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700" rel="stylesheet">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
		{% comment %} <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css"> {% endcomment %}
		<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
		 
		<link href="{% static 'css/fullcalendar.min.css' %}" rel="stylesheet" />
		<link href="{% static 'css/dataTables.bootstrap.min.css' %}" rel="stylesheet" type="text/css">
		<link rel="stylesheet" href="{% static 'css/select2.min.css' %}" type="text/css">
		<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}" type="text/css">
		<link rel="stylesheet" href="{% static 'plugins/morris/morris.css' %}">
        <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
		<!--[if lt IE 9]>
			<script src="js//html5shiv.min.js"></script>
			<script src="js/respond.min.js"></script>
		<![endif]-->
    </head>
    <body>
        <div class="main-wrapper">
            <div class="header">
                <div class="header-left">
                    <a href="index.html" class="logo">
						<img src="{% static 'images/logo.png' %}" width="40" height="40" alt="">
					</a>
					<a href="index.html" class="logo-dark">
						<img src="{% static 'images/logo-white.png' %}" width="40" height="40" alt="">
					</a>
                </div>
                <div class="page-title-box pull-left">
					<h3>{{request.user.administrator.employer.name}}</h3>
                </div>
				<a id="mobile_btn" class="mobile_btn pull-left" href="#sidebar"><i class="fa fa-bars" aria-hidden="true"></i></a>
				<ul class="nav navbar-nav navbar-right user-menu pull-right">
					<li class="dropdown hidden-xs">
						<a href="#" class="hasnotifications dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell-o"></i> <span class="badge bg-purple pull-right">3</span></a>
						<div class="dropdown-menu notifications">
							<div class="topnav-dropdown-header">
								<span>Notifications</span>
							</div>
							<div class="drop-scroll">
								<ul class="media-list scroll-content">
									<li class="media notification-message">
										<a href="activities.html">
											<div class="media-left">
												<span class="avatar">
													<img alt="John Doe" src="{% static 'images/user.jpg' %}" class="img-responsive img-circle">
												</span>
											</div>
											<div class="media-body">
												<p class="m-0 noti-details"><span class="noti-title">John Doe</span> added new task <span class="noti-title">Patient appointment booking</span></p>
												<p class="m-0"><span class="notification-time">4 mins ago</span></p>
											</div>
										</a>
									</li>
									<li class="media notification-message">
										<a href="activities.html">
											<div class="media-left">
												<span class="avatar">V</span>
											</div>
											<div class="media-body">
												<p class="m-0 noti-details"><span class="noti-title">Tarah Shropshire</span> changed the task name <span class="noti-title">Appointment booking with payment gateway</span></p>
												<p class="m-0"><span class="notification-time">6 mins ago</span></p>
											</div>
										</a>
									</li>
									<li class="media notification-message">
										<a href="activities.html">
											<div class="media-left">
												<span class="avatar">L</span>
											</div>
											<div class="media-body">
												<p class="m-0 noti-details"><span class="noti-title">Misty Tison</span> added <span class="noti-title">Domenic Houston</span> and <span class="noti-title">Claire Mapes</span> to project <span class="noti-title">Doctor available module</span></p>
												<p class="m-0"><span class="notification-time">8 mins ago</span></p>
											</div>
										</a>
									</li>
									<li class="media notification-message">
										<a href="activities.html">
											<div class="media-left">
												<span class="avatar">G</span>
											</div>
											<div class="media-body">
												<p class="m-0 noti-details"><span class="noti-title">Rolland Webber</span> completed task <span class="noti-title">Patient and Doctor video conferencing</span></p>
												<p class="m-0"><span class="notification-time">12 mins ago</span></p>
											</div>
										</a>
									</li>
									<li class="media notification-message">
										<a href="activities.html">
											<div class="media-left">
												<span class="avatar">V</span>
											</div>
											<div class="media-body">
												<p class="m-0 noti-details"><span class="noti-title">Bernardo Galaviz</span> added new task <span class="noti-title">Private chat module</span></p>
												<p class="m-0"><span class="notification-time">2 days ago</span></p>
											</div>
										</a>
									</li>
								</ul>
							</div>
							<div class="topnav-dropdown-footer">
								<a href="activities.html">View all Notifications</a>
							</div>
						</div>
					</li>
					<li class="dropdown toolbar-icon-bg hidden-xs">
						<a href="javascript:;" id="open_msg_box" class="hasnotifications"><i class="fa fa-comment-o"></i> <span class="badge bg-purple pull-right">8</span></a>
					</li>	
					<li class="dropdown">
						<a href="#" class="dropdown-toggle user-link" data-toggle="dropdown" title="Admin">
							<span class="user-img"><img class="img-circle" src="{% static 'images/user.jpg' %}" width="40" alt="Admin">
							<span class="status online"></span></span>
							<span>{{request.user.first_name}}</span>
							<small class="form-text text-muted">({{ request.user.administrator.role }})</small>
							<i class="caret"></i>
						</a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'employers:admin_profile' pk=request.user.administrator.pk %}">My Profile</a></li>
							{% if request.user.administrator.role == "admin" %}
								<li>
									<a href="{% url 'employers:edit_admin' pk=request.user.administrator.pk %}">Edit Profile</a>
								</li>
								<li><a href="{% url 'employers:settings' %}">Settings</a></li>
							{% endif %}
							<li>
								{% if request.user.is_authenticated %}
									<a href="{% url 'accounts:logout' %}">Logout</a>
								{% else %}
									<a href="{% url 'accounts:login' %}">Login</a>
								{% endif %}
							</li>
						</ul>
					</li>
				</ul>
				{% comment %} <div class="dropdown mobile-user-menu pull-right">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
					<ul class="dropdown-menu pull-right">
						<li><a href="profile.html">My Profile</a></li>
						<li><a href="edit-profile.html">Edit Profile</a></li>
						<li><a href="settings.html">Settings</a></li>
						<li><a href="login.html">Logout</a></li>
					</ul>
				</div> {% endcomment %}
            </div>
            <div class="sidebar" id="sidebar">
                <div class="sidebar-inner slimscroll">
					<div id="sidebar-menu" class="sidebar-menu">
						<ul>
							<li class="active"> 
								<a href="{% url 'employers:dashboard' %}">Dashboard</a>
							</li>
							<li class="submenu">
								<a href="#" class="noti-dot"><span> Employees</span> <span class="menu-arrow"></span></a>
								<ul class="list-unstyled" style="display: none;">
									<li><a href="{% url 'employers:employee_list' %}"><i class="fa fa-bars"></i> All Employees</a></li>
									<li><a href="{% url 'employers:upload' %}"><i class="fa fa-upload"></i>  Bulk Upload</a></li>
									<li><a href="{% url 'employers:new_employee' %}"><i class="fa fa-plus"></i> New Employee</a></li>
								</ul>
							</li>
							<li class="submenu">
								<a href="#"><span> Accounts </span> <span class="menu-arrow"></span></a>
								<ul class="list-unstyled" style="display: none;">
									<li><a href="estimates.html">Estimates</a></li>
									<li><a href="invoices.html">Invoices</a></li>
									<li><a href="payments.html">Payments</a></li>
									<li><a href="expenses.html">Expenses</a></li>
									<li><a href="provident-fund.html">Provident Fund</a></li>
									<li><a href="taxes.html">Taxes</a></li>
								</ul>
							</li>
							<li class="submenu">
								<a href="#"><span> Payroll </span> <span class="menu-arrow"></span></a>
								<ul class="list-unstyled" style="display: none;">
									<li><a href="{% url 'payroll:payrolls' %}"> Employee Payroll </a></li>
									<li><a href="{% url 'payroll:payslips' %}"> Payslips </a></li>
								</ul>
							</li>
							<li> 
								<a href="{% url 'employers:admins' %}">Users</a>
							</li>
							<li class="submenu">
								<a href="#"><span> Reports </span> <span class="menu-arrow"></span></a>
								<ul class="list-unstyled" style="display: none;">
									<li><a href="expense-reports.html"> Expense Report </a></li>
									<li><a href="invoice-reports.html"> Invoice Report </a></li>
								</ul>
							</li>
							<li> 
								<a href="{% url 'employers:settings' %}">Settings</a>
							</li>
							<li class="submenu">
								<a href="#"><span> Departments </span> 
									<span class="menu-arrow"></span></a>
								<ul class="list-unstyled" style="display: none;">
									<li><a href="{% url 'employers:dept_list' %}"> <i class="fa fa-bars"></i> All Departments </a></li>
									<li><a href="{% url 'employers:new_dept' %}"> <i class="fa fa-plus"></i> New Department </a></li>
								</ul>
							</li>
						</ul>
					</div>
                </div>
            </div>
				{% block content %}
				{% endblock %}
        </div>
		<div class="sidebar-overlay" data-reff="#sidebar"></div>
        <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.slimscroll.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/select2.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/moment.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'plugins/morris/morris.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'plugins/raphael/raphael-min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/app.js' %}"></script>
		<script>
				var data = [
			  { y: '2014', a: 50, b: 90},
			  { y: '2015', a: 65,  b: 75},
			  { y: '2016', a: 50,  b: 50},
			  { y: '2017', a: 75,  b: 60},
			  { y: '2018', a: 80,  b: 65},
			  { y: '2019', a: 90,  b: 70},
			  { y: '2020', a: 100, b: 75},
			  { y: '2021', a: 115, b: 75},
			  { y: '2022', a: 120, b: 85},
			  { y: '2023', a: 145, b: 85},
			  { y: '2024', a: 160, b: 95}
			],
			config = {
			  data: data,
			  xkey: 'y',
			  ykeys: ['a', 'b'],
			  labels: ['Total Income', 'Total Outcome'],
			  fillOpacity: 0.6,
			  hideHover: 'auto',
			  behaveLikeLine: true,
			  resize: true,
			  pointFillColors:['#ffffff'],
			  pointStrokeColors: ['black'],
				gridLineColor: '#eef0f2',
			  lineColors:['gray','orange']
		  };
		config.element = 'area-chart';
		Morris.Area(config);
		config.element = 'line-chart';
		Morris.Line(config);
		config.element = 'bar-chart';
		Morris.Bar(config);
		config.element = 'stacked';
		config.stacked = true;
		Morris.Bar(config);
		Morris.Donut({
		  element: 'pie-chart',
		  data: [
			{label: "Employees", value: 30},
			{label: "Clients", value: 15},
			{label: "Projects", value: 45},
			{label: "Tasks", value: 10}
		  ]
		});
		</script>
    </body>
</html>

templates/form.html
{% load widget_tweaks %}
{% csrf_token %}
{% if form.non_field_errors %}
    <div class="alert alert-danger">
        {% for error in form.non_field_errors %}
            {{error}}
        {% endfor %}
    </div>
{% endif %}

{% for hidden in form.hidden_fields %} {{ hidden.errors }}{{ hidden }} {% endfor %} 
{% for field in form.visible_fields %}
    <div class="form-group form-focus">
        <label class="control-label" for="{{ field.id_for_label }}">
            {{ field.label }}
        </label>
        {% if form.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                    <span class="help-block text-danger">
                        {{ error }}
                    </span>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}
        {% else %}
            {% render_field field class="form-control" %}
        {% endif %}   
    </div>
{% endfor %}

templates/split_form.html
{% load widget_tweaks %}
<div class="row">
    {% csrf_token %} 
    {% if form.non_field_errors %}
        <div class="alert alert-danger">
            {% for error in form.non_field_errors %} {{error}} {% endfor %}
        </div>
    {% endif %} 
    {% for hidden in form.hidden_fields %} {{ hidden.errors }}{{ hidden }} {% endfor %} 
    {% for field in form.visible_fields %}
        <div class="col-md-6">
            <div class="form-group">
                <label class="control-label" for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
                {% if form.is_bound %} 
                    {% if field.errors %} 
                        {% render_field field class="form-control is-invalid" %} 
                        {% for error in field.errors %}
                            <span class="help-block text-danger">
                                {{ error }}
                            </span>
                        {% endfor %} 
                    {% else %} 
                        {% render_field field class="form-control is-valid" %} 
                    {% endif %} 
                {% else %} 
                    {% render_field field class="form-control" %} 
                {% endif %} 
            </div>
        </div>
    {% endfor %}
</div>

templates/split_form_address.html
{% load widget_tweaks %}
<div class="row">
    {% csrf_token %} 
    {% if form.non_field_errors %}
        <div class="alert alert-danger">
            {% for error in form.non_field_errors %} {{error}} {% endfor %}
        </div>
    {% endif %}
    {% if addr.non_field_errors %}
        <div class="alert alert-danger">
            {% for error in addr.non_field_errors %} {{error}} {% endfor %}
        </div>
    {% endif %} 
    {% for hidden in form.hidden_fields %} {{ hidden.errors }}{{ hidden }} {% endfor %} 
    {% for hidden in addr.hidden_fields %} {{ hidden.errors }}{{ hidden }} {% endfor %} 
    {% for field in form.visible_fields %}
        <div class="col-md-6">
            <div class="form-group">
                <label class="control-label" for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
                {% if form.is_bound %} 
                    {% if field.errors %} 
                        {% render_field field class="form-control is-invalid" %} 
                        {% for error in field.errors %}
                            <span class="help-block text-danger">
                                {{ error }}
                            </span>
                        {% endfor %} 
                    {% else %} 
                        {% render_field field class="form-control is-valid" %} 
                    {% endif %} 
                {% else %} 
                    {% render_field field class="form-control" %} 
                {% endif %}
            </div>
        </div>
    {% endfor %}
    {% for field in addr.visible_fields %}
        <div class="col-md-6">
            <div class="form-group">
                <label class="control-label" for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
                {% if addr.is_bound %} 
                    {% if field.errors %} 
                        {% render_field field class="form-control is-invalid" %} 
                        {% for error in field.errors %}
                            <span class="help-block text-danger">
                                {{ error }}
                            </span>
                        {% endfor %} 
                    {% else %} 
                        {% render_field field class="form-control is-valid" %} 
                    {% endif %} 
                {% else %} 
                    {% render_field field class="form-control" %} 
                {% endif %}
            </div>
        </div>
    {% endfor %}
</div>