api/urls.py
from django.urls import path
from api import views

app_name = "api"
urlpatterns = [
    path("transact/",views.run_transaction,name="transact"),
    path("transact/verify/",views.verify_transaction,name="verify"),
    path("transact/resend/",views.resend_code,name="resend")
]

payroll/urls.py
from django.urls import path
from payroll import views

app_name = "payroll"
urlpatterns = [
    path("", views.payroll_list, name="payrolls"),
    path("generate/", views.generate_payrolls, name="gen_pay"),
    path("payslips/", views.generate_payslips, name="payslips")
]

payroll/models.py
import os
from decimal import Decimal
from django.db import models
from employers.models import Employee
from common.models import BaseModel
from common.gra import get_tax
from django.conf import settings

# Create your models here.


class Payroll(BaseModel):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    basic_salary = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)
    bonus = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)
    allowances = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)
    deductions = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)
    gross_salary = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)
    ssf_employee = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)
    ssf_employer = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)
    taxable_income = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)
    paye = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)
    net_salary = models.DecimalField(
        null=True, blank=True, max_digits=12, decimal_places=2)

    @property
    def employer(self):
        return self.employee.employer

    @property
    def month(self):
        return self.created_at.month

    @property
    def year(self):
        return self.created_at.year

    @property
    def name(self):
        return "{0}_{1}".format(self.month, self.year)

    def save(self, *args, **kwargs):
        self.basic_salary = self.employee.workdetail.basic_salary
        self.allowances = self.employee.paymentdetail.allowances
        self.bonus = self.employee.paymentdetail.bonus
        self.deductions = self.employee.paymentdetail.deductions
        self.gross_salary = self.basic_salary + self.bonus + self.allowances
        self.ssf_employee = self.gross_salary * settings.SSF_EMPLOYEE_RATE
        self.ssf_employer = self.gross_salary * settings.SSF_EMPLOYER_RATE
        self.taxable_income = self.gross_salary - self.ssf_employee
        self.paye = get_tax(self.taxable_income)
        self.net_salary = self.taxable_income - self.deductions
        super().save(*args, **kwargs)

payroll/views.py
import datetime as dt
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from payroll.models import Employee, Payroll
from common.decorators import admin_staff_required

# Create your views here.
@login_required
@admin_staff_required
def generate_payrolls(request):
    employer = request.user.administrator.employer
    for employee in Employee.objects.filter(employer=employer, active=True):
        Payroll.objects.create(employee=employee)
    return redirect("payroll:payrolls")


@login_required
def payroll_list(request):
    employer = request.user.administrator.employer
    payrolls = Payroll.objects.filter(employee__employer=employer)
    return render(request, "payroll/payrolls.html", {"payrolls": payrolls})


@login_required
def generate_payslips(request):
    return render(request, "payroll/payslips.html")

payroll/templates/payroll/payrolls.html
{% extends "employer_base.html" %}
{% load humanize %}
{% block title %}Payroll {% endblock %}
{% block content %}
    <div class="page-wrapper">
        <div class="content container-fluid">
            <div class="row">
                <div class="col-xs-4">
                    <h4 class="page-title">Employee Payroll</h4>
                </div>
                <div class="col-xs-8 text-right m-b-30">
                    <a href="{% url 'payroll:gen_pay' %}" class="btn btn-primary rounded pull-right">
                        <i class="fa fa-plus"></i> Generate Payrolls</a>
                </div>
            </div>
            <div class="row filter-row">
                <div class="col-sm-3 col-md-2 col-xs-6">
                    <div class="form-group ">
                        <label class="control-label">Employee Name</label>
                        <input type="text" class="form-control floating" />
                    </div>
                </div>
                <div class="col-sm-3 col-md-2 col-xs-6">
                    <div class="form-group  select-focus">
                        <label class="control-label">Role</label>
                        <select class="select floating">
                            <option value=""> -- Select -- </option>
                            <option value="">Employee</option>
                            <option value="1">Manager</option>
                        </select>
                    </div>
                </div>
                <div class="col-sm-3 col-md-2 col-xs-6">
                    <div class="form-group  select-focus">
                        <label class="control-label">Leave Status</label>
                        <select class="select floating">
                            <option value=""> -- Select -- </option>
                            <option value="0"> Pending </option>
                            <option value="1"> Approved </option>
                            <option value="2"> Rejected </option>
                        </select>
                    </div>
                </div>
                <div class="col-sm-3 col-md-2 col-xs-6">
                    <div class="form-group ">
                        <label class="control-label">From</label>
                        <div class="cal-icon">
                            <input class="form-control floating datetimepicker" type="text">
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 col-md-2 col-xs-6">
                    <div class="form-group ">
                        <label class="control-label">To</label>
                        <div class="cal-icon">
                            <input class="form-control floating datetimepicker" type="text">
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 col-md-2 col-xs-6">
                    <a href="#" class="btn btn-success btn-block"> Search </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table table-striped custom-table datatable">
                            <thead>
                                <tr>
                                    <th style="width:10%;">Employee</th>
                                    <th>Basic Salary</th>
                                    <th>Bonus</th>
                                    <th>Allowances</th>
                                    <th>Gross Salary</th>
                                    <th>SSF</th>
                                    <th>SSF Employer</th>
                                    <th>Taxable</th>
                                    <th>P.A.Y.E</th>
                                    <th>Net Salary</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for payroll in payrolls %}
                                    <tr>
                                        <td>{{payroll.employee}}</td>
                                        <td>{{payroll.basic_salary|intcomma}}</td>
                                        <td>{{payroll.bonus|intcomma}}</td>
                                        <td>{{payroll.allowances|intcomma}}</td>
                                        <td>{{payroll.gross_salary|intcomma}}</td>
                                        <td>{{payroll.ssf_employee|intcomma}}</td>
                                        <td>{{payroll.ssf_employer|intcomma}}</td>
                                        <td>{{payroll.taxable_income|intcomma}}</td>
                                        <td>{{payroll.paye|intcomma}}</td>
                                        <td>{{payroll.net_salary|intcomma}}</td>
                                    </tr>
                                {% empty %}
                                    <p class="alert alert-danger">Sorry No Payrolls yet</p>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

payroll/templates/payroll/payslips.html
{% extends "employer_base.html" %}
{% block title %}Payslips{% endblock %}
{% block content %}
    <div class="page-wrapper">
        <div class="content container-fluid">
            <div class="row">
                <div class="col-xs-8">
                    <h4 class="page-title">Payslip</h4>
                </div>
                <div class="col-sm-4 text-right m-b-30">
                    <div class="btn-group btn-group-sm">
                        <button class="btn btn-default">CSV</button>
                        <button class="btn btn-default">PDF</button>
                        <button class="btn btn-default">
                            <i class="fa fa-print fa-lg"></i> Print</button>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card-box">
                        <h4 class="payslip-title">Payslip for the month of September 2017</h4>
                        <div class="row">
                            <div class="col-md-6 m-b-20">
                                <img src="images/logo2.png" class="m-b-20 mt-10" alt="" style="width: 100px;">
                                <ul class="list-unstyled m-b-0">
                                    <li>Focus Technologies</li>
                                    <li>3864 Quiet Valley Lane,</li>
                                    <li>Sherman Oaks, CA, 91403</li>
                                </ul>
                            </div>
                            <div class="col-md-6 m-b-20">
                                <div class="invoice-details">
                                    <h3 class="text-uppercase">Payslip #49029</h3>
                                    <ul class="list-unstyled">
                                        <li>Salary Month:
                                            <span>September, 2017</span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 m-b-20">
                                <ul class="list-unstyled">
                                    <li>
                                        <h5 class="m-b-0">
                                            <strong>John Doe</strong>
                                        </h5>
                                    </li>
                                    <li>
                                        <span>Web Designer</span>
                                    </li>
                                    <li>Employee ID: FT-0009</li>
                                    <li>Joining Date: 1 Jan 2013</li>
                                </ul>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div>
                                    <h4 class="m-b-10">
                                        <strong>Earnings</strong>
                                    </h4>
                                    <table class="table table-bordered">
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <strong>Basic Salary</strong>
                                                    <span class="pull-right">$6500</span>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <strong>House Rent Allowance (H.R.A.)</strong>
                                                    <span class="pull-right">$55</span>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <strong>Conveyance</strong>
                                                    <span class="pull-right">$55</span>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <strong>Other Allowance</strong>
                                                    <span class="pull-right">$55</span>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <strong>Total Earnings</strong>
                                                    <span class="pull-right">
                                                        <strong>$55</strong>
                                                    </span>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div>
                                    <h4 class="m-b-10">
                                        <strong>Deductions</strong>
                                    </h4>
                                    <table class="table table-bordered">
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <strong>Tax Deducted at Source (T.D.S.)</strong>
                                                    <span class="pull-right">$0</span>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <strong>Provident Fund</strong>
                                                    <span class="pull-right">$0</span>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <strong>ESI</strong>
                                                    <span class="pull-right">$0</span>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <strong>Loan</strong>
                                                    <span class="pull-right">$300</span>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <strong>Total Deductions</strong>
                                                    <span class="pull-right">
                                                        <strong>$59698</strong>
                                                    </span>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <p>
                                    <strong>Net Salary: $59698</strong> (Fifty nine thousand six hundred and ninety eight only.)</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}